<a href="https://colab.research.google.com/github/emmanresu/Thesis-Keras/blob/feature%2Fprototype/EDA_indian_food_prices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [41]:
prices = pd.read_csv('wfp_food_prices_ind.csv')

In [42]:
prices

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
0,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,cereals and tubers,Rice,52,KG,actual,Retail,INR,8.00,0.26
1,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,cereals and tubers,Wheat,84,KG,actual,Retail,INR,5.00,0.16
2,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,miscellaneous food,Sugar,97,KG,actual,Retail,INR,13.50,0.43
3,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,oil and fats,Oil (mustard),228,KG,actual,Retail,INR,31.00,0.99
4,1994-01-15,Gujarat,Ahmadabad,Ahmedabad,923,23.03,72.62,cereals and tubers,Rice,52,KG,actual,Retail,INR,6.80,0.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206087,2026-05-15,Rajasthan,Jaipur,North Zone,9638,26.94,75.80,vegetables and fruits,Eggplants,434,KG,actual,Retail,INR,35.35,0.37
206088,2026-05-15,Rajasthan,Jaipur,North Zone,9638,26.94,75.80,vegetables and fruits,Garlic,105,KG,actual,Retail,INR,34.86,0.36
206089,2026-05-15,Rajasthan,Jaipur,North Zone,9638,26.94,75.80,vegetables and fruits,Ginger,712,KG,actual,Retail,INR,27.01,0.28
206090,2026-05-15,Rajasthan,Jaipur,North Zone,9638,26.94,75.80,vegetables and fruits,Onions,173,KG,actual,Retail,INR,23.82,0.25
206091,2026-05-15,Rajasthan,Jaipur,North Zone,9638,26.94,75.80,vegetables and fruits,Tomatoes,114,KG,actual,Retail,INR,28.69,0.30

In [43]:
prices.shape

(206092, 16)

In [44]:
prices.describe()

,market_id,latitude,longitude,commodity_id,price,usdprice
count,206092.000000,205366.000000,205366.000000,206092.000000,206092.000000,206092.000000
mean,2461.464074,22.369520,80.259819,189.204341,94.468171,1.391436
std,2172.446129,6.207687,5.656315,124.364190,213.563321,3.638336
min,921.000000,8.510000,69.670000,52.000000,2.500000,0.057000
25%,940.000000,18.860000,76.280000,83.000000,28.000000,0.410000
50%,962.000000,23.350000,78.160000,173.000000,52.630000,0.750000
75%,4672.000000,26.640000,84.900000,325.000000,109.000000,1.500000
max,9642.000000,32.550000,94.120000,1341.000000,4910.000000,88.820000

In [45]:
rice_prices = prices.query('commodity == "Rice"')

In [65]:
print(rice_prices[['date', 'market', 'unit', 'priceflag', 'price']].to_string())

              date                   market    unit priceflag    price
0       1994-01-15                    Delhi      KG    actual     8.00
4       1994-01-15                Ahmedabad      KG    actual     6.80
8       1994-01-15                   Shimla      KG    actual     9.00
11      1994-01-15                Bengaluru      KG    actual     6.50
18      1994-01-15                   Mumbai      KG    actual     7.50
22      1994-01-15             Bhubaneshwar      KG    actual     5.00
26      1994-01-15                Hyderabad      KG    actual     6.20
32      1994-01-15                  Kolkata      KG    actual     6.75
35      1994-02-15                    Delhi      KG    actual     8.00
39      1994-02-15                Ahmedabad      KG    actual     6.90
43      1994-02-15                   Shimla      KG    actual     8.75
46      1994-02-15                   Bhopal      KG    actual     6.25
49      1994-02-15                   Mumbai      KG    actual     8.00
52      1994-02-15                 Shillong      KG    actual     8.00
55      1994-02-15             Bhubaneshwar      KG    actual     5.00
59      1994-02-15                   Jaipur      KG    actual     9.00
63      1994-02-15                  Chennai      KG    actual     7.00
67      1994-02-15                Hyderabad      KG    actual     7.00
71      1994-03-15                 Guwahati      KG    actual     6.50
74      1994-03-15                    Delhi      KG    actual     8.00
78      1994-03-15                Ahmedabad      KG    actual     7.25
81      1994-03-15                   Shimla      KG    actual     9.00
84      1994-03-15                Bengaluru      KG    actual     7.50
87      1994-03-15         Tiruvanantapuram      KG    actual     8.20
92      1994-03-15                   Mumbai      KG    actual     8.00
95      1994-03-15                 Shillong      KG    actual     7.00
99      1994-03-15             Bhubaneshwar      KG    actual     5.20
102     1994-03-15                   Jaipur      KG    actual     9.00
106     1994-03-15                  Chennai      KG    actual     7.00
110     1994-03-15                Hyderabad      KG    actual     7.00
116     1994-03-15                  Lucknow      KG    actual     6.00
120     1994-03-15                  Kolkata      KG    actual     6.80
123     1994-04-15                    Delhi      KG    actual     8.50
127     1994-04-15                Ahmedabad      KG    actual     7.25
131     1994-04-15                   Shimla      KG    actual     9.00
134     1994-04-15                Bengaluru      KG    actual     7.50
138     1994-04-15         Tiruvanantapuram      KG    actual     8.40
143     1994-04-15                   Mumbai      KG    actual     8.00
147     1994-04-15                   Aizawl      KG    actual     7.00
149     1994-04-15                   Jaipur      KG    actual     9.50
152     1994-04-15                  Chennai      KG    actual     7.25
155     1994-04-15                Hyderabad      KG    actual     7.00
159     1994-04-15                  Kolkata      KG    actual     6.80
162     1994-05-15                    Delhi      KG    actual     8.50
166     1994-05-15                Ahmedabad      KG    actual     6.80
170     1994-05-15                   Shimla      KG    actual     9.25
177     1994-05-15                   Mumbai      KG    actual     8.00
181     1994-05-15                   Jaipur      KG    actual     9.75
185     1994-05-15                  Chennai      KG    actual     7.25
189     1994-05-15                Hyderabad      KG    actual     6.50
195     1994-05-15                  Kolkata      KG    actual     6.90
198     1994-06-15                 Guwahati      KG    actual     7.40
201     1994-06-15                    Delhi      KG    actual     8.50
205     1994-06-15                   Shimla      KG    actual     9.25
208     1994-06-15                   Bhopal      KG    actual     7.00
211     1994-06-15                   Mumbai      KG    actual    10.00
214     1994-06-15             Bhubaneshwar      KG    actual     5.50
218     1994-06-15                   Jaipur      KG    actual     9.75
222     1994-06-15                  Chennai      KG    actual     7.50
226     1994-06-15                Hyderabad      KG    actual     6.80
232     1994-07-15                 Guwahati      KG    actual     7.20
235     1994-07-15                    Delhi      KG    actual     8.50
239     1994-07-15                   Shimla      KG    actual     9.50
245     1994-07-15         Tiruvanantapuram      KG    actual     9.60
248     1994-07-15                   Bhopal      KG    actual     7.25
252     1994-07-15                   Mumbai      KG    actual     8.00
255     1994-07-15             Bhubaneshwar      KG    actual     6.00
259     1994-07-15                   Jaipur      KG    actual     9.75
263     1994-07-15                  Chennai      KG    actual     7.50
267     1994-07-15                Hyderabad      KG    actual     6.80
273     1994-07-15                  Kolkata      KG    actual     8.50
276     1994-08-15                 Guwahati      KG    actual     7.00
279     1994-08-15                    Delhi      KG    actual     8.50
283     1994-08-15                Ahmedabad      KG    actual     7.60
286     1994-08-15                   Shimla      KG    actual     9.50
292     1994-08-15         Tiruvanantapuram      KG    actual     9.20
294     1994-08-15                   Bhopal      KG    actual     7.50
297     1994-08-15                   Mumbai      KG    actual     8.50
301     1994-08-15                 Shillong      KG    actual     7.70
305     1994-08-15             Bhubaneshwar      KG    actual     6.20
309     1994-08-15                   Jaipur      KG    actual    10.00
313     1994-08-15                  Chennai      KG    actual     7.50
317     1994-08-15                Hyderabad      KG    actual     6.80
323     1994-08-15                  Kolkata      KG    actual     8.75
327     1994-09-15                 Guwahati      KG    actual     7.50
330     1994-09-15                    Delhi      KG    actual     8.50
334     1994-09-15                Ahmedabad      KG    actual     7.80
338     1994-09-15                   Shimla      KG    actual     9.50
341     1994-09-15         Tiruvanantapuram      KG    actual     9.80
344     1994-09-15                   Bhopal      KG    actual     7.50
347     1994-09-15                   Mumbai      KG    actual     8.00
353     1994-09-15             Bhubaneshwar      KG    actual     6.50
357     1994-09-15                   Jaipur      KG    actual    10.00
361     1994-09-15                  Chennai      KG    actual     7.80
365     1994-09-15                Hyderabad      KG    actual     6.80
371     1994-09-15                  Kolkata      KG    actual     8.75
375     1994-10-15                 Guwahati      KG    actual     7.20
378     1994-10-15                    Delhi      KG    actual     8.50
382     1994-10-15                   Shimla      KG    actual     9.25
388     1994-10-15                   Bhopal      KG    actual     8.00
392     1994-10-15                   Mumbai      KG    actual     8.00
395     1994-10-15                 Shillong      KG    actual     7.60
399     1994-10-15             Bhubaneshwar      KG    actual     6.40
403     1994-10-15                  Chennai      KG    actual     7.80
407     1994-10-15                Hyderabad      KG    actual     6.50
413     1994-10-15                  Kolkata      KG    actual     8.75
417     1994-11-15                 Guwahati      KG    actual     7.00
420     1994-11-15                    Delhi      KG    actual     8.50
424     1994-11-15                Ahmedabad      KG    actual     8.50
427     1994-11-15                   Shimla      KG    actual     9.25
433     1994-11-15         Tiruvanantapuram      KG    actual    10.00
435     1994-11-15                   Bhopal      KG    actual     8.00
439     1994-11-15                   Mumbai      KG    actual     9.00
442     1994-11-15                 Shillong      KG    actual     7.60
448     1994-11-15             Bhubaneshwar      KG    actual     6.50
452     1994-11-15                   Jaipur      KG    actual    11.00
456     1994-11-15                  Chennai      KG    actual     7.80
460     1994-11-15                Hyderabad      KG    actual     7.00
469     1994-11-15                  Kolkata      KG    actual     8.75
473     1994-12-15                 Guwahati      KG    actual     7.00
476     1994-12-15                    Patna      KG    actual     8.20
480     1994-12-15                    Delhi      KG    actual     8.50
483     1994-12-15                Ahmedabad      KG    actual     8.40
487     1994-12-15                   Shimla      KG    actual     9.50
490     1994-12-15                Bengaluru      KG    actual     7.20
493     1994-12-15         Tiruvanantapuram      KG    actual    11.00
496     1994-12-15                   Bhopal      KG    actual     8.00
500     1994-12-15                   Mumbai      KG    actual     8.00
504     1994-12-15                 Shillong      KG    actual     7.00
510     1994-12-15             Bhubaneshwar      KG    actual     6.00
514     1994-12-15                   Jaipur      KG    actual    11.00
518     1994-12-15                  Chennai      KG    actual     8.20
522     1994-12-15                Hyderabad      KG    actual     7.00
528     1994-12-15                  Kolkata      KG    actual     7.70
532     1995-01-15                   Bhopal      KG    actual     8.00
534     1995-01-15                   Mumbai      KG    actual     8.70
536     1995-01-15                 Shillong      KG    actual     7.00
538     1995-01-15             Bhubaneshwar      KG    actual     6.20
540     1995-01-15                   Jaipur      KG    actual    11.00
542     1995-01-15                  Chennai      KG    actual     8.00
544     1995-01-15                  Lucknow      KG    actual     5.50
547     1995-02-15                   Bhopal      KG    actual     7.50
549     1995-02-15                   Mumbai      KG    actual     8.50
551     1995-02-15                 Shillong      KG    actual     7.50
553     1995-02-15                   Aizawl      KG    actual     7.00
554     1995-02-15             Bhubaneshwar      KG    actual     6.00
556     1995-02-15                  Chennai      KG    actual     7.60
557     1995-02-15                  Lucknow      KG    actual     5.90
559     1995-02-15                  Kolkata      KG    actual     9.00
561     1995-03-15                   Bhopal      KG    actual     7.75
563     1995-03-15                   Mumbai      KG    actual     8.50
565     1995-03-15                 Shillong      KG    actual     7.80
567     1995-03-15                   Aizawl      KG    actual     7.00
568     1995-03-15             Bhubaneshwar      KG    actual     6.20
570     1995-03-15                   Jaipur      KG    actual    11.00
571     1995-03-15                  Chennai      KG    actual     7.50
572     1995-03-15                  Kolkata      KG    actual     9.00
574     1995-04-15                   Bhopal      KG    actual     7.25
576     1995-04-15                   Mumbai      KG    actual     9.00
578     1995-04-15                 Shillong      KG    actual     8.00
580     1995-04-15                   Aizawl      KG    actual     7.00
581     1995-04-15             Bhubaneshwar      KG    actual     6.50
583     1995-04-15                   Jaipur      KG    actual    11.00
585     1995-04-15                  Chennai      KG    actual     7.70
586     1995-04-15                  Kolkata      KG    actual     9.00
589     1995-05-15                   Mumbai      KG    actual     8.50
590     1995-05-15                 Shillong      KG    actual     7.80
592     1995-05-15                   Aizawl      KG    actual     7.00
593     1995-05-15             Bhubaneshwar      KG    actual     7.40
595     1995-05-15                   Jaipur      KG    actual    11.00
597     1995-05-15                  Chennai      KG    actual     8.00
599     1995-05-15                  Lucknow      KG    actual     6.50
601     1995-05-15                  Kolkata      KG    actual     9.00
604     1995-06-15                   Mumbai      KG    actual     8.50
605     1995-06-15                 Shillong      KG    actual     7.60
607     1995-06-15                   Aizawl      KG    actual     7.00
608     1995-06-15             Bhubaneshwar      KG    actual     7.00
610     1995-06-15                   Jaipur      KG    actual    10.00
612     1995-06-15                  Chennai      KG    actual     8.00
614     1995-06-15                  Lucknow      KG    actual     7.50
616     1995-06-15                  Kolkata      KG    actual     9.00
619     1995-07-15                   Mumbai      KG    actual     8.50
621     1995-07-15             Bhubaneshwar      KG    actual     7.00
623     1995-07-15                   Jaipur      KG    actual     9.50
625     1995-07-15                  Chennai      KG    actual     8.50
627     1995-07-15                  Kolkata      KG    actual     9.00
630     1995-08-15                   Mumbai      KG    actual     8.50
632     1995-08-15                 Shillong      KG    actual     7.80
634     1995-08-15             Bhubaneshwar      KG    actual     8.80
635     1995-08-15                   Jaipur      KG    actual     9.50
637     1995-08-15                  Chennai      KG    actual     8.00
639     1995-08-15                  Kolkata      KG    actual     9.50
642     1995-09-15                   Mumbai      KG    actual     9.00
644     1995-09-15                 Shillong      KG    actual     7.80
646     1995-09-15             Bhubaneshwar      KG    actual     6.80
647     1995-09-15                   Jaipur      KG    actual     9.50
649     1995-09-15                  Chennai      KG    actual     8.50
651     1995-09-15                  Lucknow      KG    actual     6.50
653     1995-09-15                  Kolkata      KG    actual     9.50
655     1995-10-15                   Bhopal      KG    actual     7.50
657     1995-10-15                   Mumbai      KG    actual     9.00
659     1995-10-15                 Shillong      KG    actual     7.30
661     1995-10-15             Bhubaneshwar      KG    actual     7.20
662     1995-10-15                   Jaipur      KG    actual     9.50
664     1995-10-15                  Chennai      KG    actual     8.00
666     1995-10-15                  Lucknow      KG    actual     6.50
668     1995-10-15                  Kolkata      KG    actual     9.50
670     1995-11-15                   Bhopal      KG    actual     7.50
672     1995-11-15                   Mumbai      KG    actual     9.00
674     1995-11-15                 Shillong      KG    actual     7.80
676     1995-11-15             Bhubaneshwar      KG    actual     7.50
677     1995-11-15                   Jaipur      KG    actual     9.00
679     1995-11-15                  Chennai      KG    actual     8.50
681     1995-11-15                  Lucknow      KG    actual     6.10
683     1995-11-15                  Kolkata      KG    actual     9.50
686     1995-12-15                   Bhopal      KG    actual     7.50
688     1995-12-15                   Mumbai      KG    actual     9.00
690     1995-12-15                 Shillong      KG    actual     7.40
692     1995-12-15             Bhubaneshwar      KG    actual     7.50
693     1995-12-15                   Jaipur      KG    actual     9.50
695     1995-12-15                  Chennai      KG    actual     8.50
698     1995-12-15                  Kolkata      KG    actual     9.50
700     1996-01-15                 Guwahati      KG    actual     7.50
703     1996-01-15                    Delhi      KG    actual     9.50
707     1996-01-15                Ahmedabad      KG    actual     8.50
711     1996-01-15                Bengaluru      KG    actual     9.50
714     1996-01-15         Tiruvanantapuram      KG    actual    11.00
717     1996-01-15                   Bhopal      KG    actual     7.15
720     1996-01-15                   Mumbai      KG    actual     9.00
723     1996-01-15                 Shillong      KG    actual     7.50
727     1996-01-15                   Aizawl      KG    actual     7.00
729     1996-01-15             Bhubaneshwar      KG    actual     6.50
732     1996-01-15                   Jaipur      KG    actual     9.50
736     1996-01-15                  Chennai      KG    actual     8.75
740     1996-01-15                Hyderabad      KG    actual     7.50
744     1996-01-15                 Agartala      KG    actual     8.00
747     1996-01-15                  Lucknow      KG    actual     6.60
754     1996-02-15                 Guwahati      KG    actual     8.00
757     1996-02-15                    Patna      KG    actual     8.00
761     1996-02-15                    Delhi      KG    actual     9.50
765     1996-02-15                Ahmedabad      KG    actual     8.80
769     1996-02-15                   Shimla      KG    actual    10.00
772     1996-02-15                Bengaluru      KG    actual    10.50
776     1996-02-15         Tiruvanantapuram      KG    actual    12.50
779     1996-02-15                   Bhopal      KG    actual     7.50
783     1996-02-15                   Mumbai      KG    actual     9.00
786     1996-02-15                 Shillong      KG    actual     8.00
790     1996-02-15                   Aizawl      KG    actual     7.00
792     1996-02-15             Bhubaneshwar      KG    actual     6.50
795     1996-02-15                   Jaipur      KG    actual     9.50
799     1996-02-15                  Chennai      KG    actual     8.75
803     1996-02-15                Hyderabad      KG    actual     7.80
809     1996-02-15                  Lucknow      KG    actual     7.70
813     1996-02-15                  Kolkata      KG    actual     9.80
817     1996-03-15                 Guwahati      KG    actual     7.50
820     1996-03-15                    Patna      KG    actual     8.00
824     1996-03-15                    Delhi      KG    actual    10.00
828     1996-03-15                Ahmedabad      KG    actual     9.50
831     1996-03-15                   Shimla      KG    actual    11.00
837     1996-03-15         Tiruvanantapuram      KG    actual    13.00
840     1996-03-15                   Bhopal      KG    actual     7.50
844     1996-03-15                   Mumbai      KG    actual     9.00
847     1996-03-15                 Shillong      KG    actual     7.70
853     1996-03-15             Bhubaneshwar      KG    actual     6.50
856     1996-03-15                   Jaipur      KG    actual     9.50
860     1996-03-15                  Chennai      KG    actual     8.80
863     1996-03-15                Hyderabad      KG    actual     7.50
867     1996-03-15                 Agartala      KG    actual     8.50
870     1996-03-15                  Lucknow      KG    actual     6.50
874     1996-03-15                  Kolkata      KG    actual    10.00
878     1996-04-15                 Guwahati      KG    actual     8.00
881     1996-04-15                    Patna      KG    actual     9.00
885     1996-04-15                    Delhi      KG    actual    11.00
889     1996-04-15                Ahmedabad      KG    actual     9.50
893     1996-04-15                   Shimla      KG    actual    10.75
899     1996-04-15         Tiruvanantapuram      KG    actual    13.00
904     1996-04-15                   Mumbai      KG    actual     9.00
908     1996-04-15                 Shillong      KG    actual     8.30
914     1996-04-15             Bhubaneshwar      KG    actual     6.80
917     1996-04-15                   Jaipur      KG    actual    10.00

In [47]:
rice_prices['date'].unique()

array(['1994-01-15', '1994-02-15', '1994-03-15', '1994-04-15',
       '1994-05-15', '1994-06-15', '1994-07-15', '1994-08-15',
       '1994-09-15', '1994-10-15', '1994-11-15', '1994-12-15',
       '1995-01-15', '1995-02-15', '1995-03-15', '1995-04-15',
       '1995-05-15', '1995-06-15', '1995-07-15', '1995-08-15',
       '1995-09-15', '1995-10-15', '1995-11-15', '1995-12-15',
       '1996-01-15', '1996-02-15', '1996-03-15', '1996-04-15',
       '1996-05-15', '1996-06-15', '1996-07-15', '1996-08-15',
       '1996-09-15', '1996-10-15', '1996-11-15', '1996-12-15',
       '1997-01-15', '1997-02-15', '1997-03-15', '1997-04-15',
       '1997-05-15', '1997-06-15', '1997-07-15', '1997-08-15',
       '1997-09-15', '1997-10-15', '1997-11-15', '1997-12-15',
       '1998-01-15', '1998-02-15', '1998-03-15', '1998-04-15',
       '1998-05-15', '1998-06-15', '1998-07-15', '1998-08-15',
       '1998-09-15', '1998-10-15', '1998-11-15', '1998-12-15',
       '1999-01-15', '1999-02-15', '1999-03-15', '1999-04-15',
       '1999-05-15', '1999-06-15', '1999-07-15', '1999-08-15',
       '1999-09-15', '1999-10-15', '1999-11-15', '1999-12-15',
       '2000-01-15', '2000-02-15', '2000-03-15', '2000-04-15',
       '2000-05-15', '2000-06-15', '2000-07-15', '2000-08-15',
       '2000-09-15', '2000-10-15', '2000-11-15', '2000-12-15',
       '2001-01-15', '2001-02-15', '2001-03-15', '2001-04-15',
       '2001-05-15', '2001-06-15', '2001-07-15', '2001-08-15',
       '2001-09-15', '2001-10-15', '2001-11-15', '2001-12-15',
       '2002-01-15', '2002-02-15', '2002-03-15', '2002-04-15',
       '2002-05-15', '2002-06-15', '2002-07-15', '2002-08-15',
       '2002-09-15', '2002-10-15', '2002-11-15', '2002-12-15',
       '2003-01-15', '2003-02-15', '2003-03-15', '2003-04-15',
       '2003-05-15', '2003-06-15', '2003-07-15', '2003-08-15',
       '2003-09-15', '2003-10-15', '2003-11-15', '2003-12-15',
       '2004-01-15', '2004-02-15', '2004-03-15', '2004-04-15',
       '2004-05-15', '2004-06-15', '2004-07-15', '2004-08-15',
       '2004-09-15', '2004-10-15', '2004-11-15', '2004-12-15',
       '2005-01-15', '2005-02-15', '2005-03-15', '2005-04-15',
       '2005-05-15', '2005-06-15', '2005-07-15', '2005-08-15',
       '2005-09-15', '2005-10-15', '2005-11-15', '2005-12-15',
       '2006-01-15', '2006-02-15', '2006-03-15', '2006-04-15',
       '2006-05-15', '2006-06-15', '2006-07-15', '2006-08-15',
       '2006-09-15', '2006-10-15', '2006-11-15', '2006-12-15',
       '2007-01-15', '2007-02-15', '2007-03-15', '2007-04-15',
       '2007-05-15', '2007-06-15', '2007-07-15', '2007-08-15',
       '2007-09-15', '2007-10-15', '2007-11-15', '2007-12-15',
       '2008-01-15', '2008-02-15', '2008-03-15', '2008-04-15',
       '2008-05-15', '2008-06-15', '2008-07-15', '2008-08-15',
       '2008-09-15', '2008-10-15', '2008-11-15', '2008-12-15',
       '2009-01-15', '2009-02-15', '2009-03-15', '2009-04-15',
       '2009-05-15', '2009-06-15', '2009-07-15', '2009-08-15',
       '2009-09-15', '2009-10-15', '2009-11-15', '2009-12-15',
       '2010-01-15', '2010-02-15', '2010-03-15', '2010-04-15',
       '2010-05-15', '2010-06-15', '2010-07-15', '2010-08-15',
       '2010-09-15', '2010-10-15', '2010-11-15', '2010-12-15',
       '2011-01-15', '2011-02-15', '2011-03-15', '2011-04-15',
       '2011-05-15', '2011-06-15', '2011-07-15', '2011-08-15',
       '2011-09-15', '2011-10-15', '2011-11-15', '2011-12-15',
       '2012-01-15', '2012-02-15', '2012-03-15', '2012-04-15',
       '2012-05-15', '2012-06-15', '2012-07-15', '2012-08-15',
       '2012-09-15', '2012-10-15', '2012-11-15', '2012-12-15',
       '2013-01-15', '2013-02-15', '2013-03-15', '2013-04-15',
       '2013-05-15', '2013-06-15', '2013-07-15', '2013-08-15',
       '2013-09-15', '2013-10-15', '2013-11-15', '2013-12-15',
       '2014-01-15', '2014-02-15', '2014-03-15', '2014-04-15',
       '2014-05-15', '2014-06-15', '2014-07-15', '2014-08-15',
       '2014-09-15', '2014-10-15', '2014-11-15', '2014-12-15',
       '2015-01-15', '2015-02-15', '2015-03-15', '2015-04-15',
       '2015-05-15', '2015-06-15', '2015-07-15', '2015-08-15',
       '2015-09-15', '2015-10-15', '2015-11-15', '2015-12-15',
       '2016-01-15', '2016-02-15', '2016-03-15', '2016-04-15',
       '2016-05-15', '2016-06-15', '2016-07-15', '2016-08-15',
       '2016-09-15', '2016-10-15', '2016-11-15', '2016-12-15',
       '2017-01-15', '2017-02-15', '2017-03-15', '2017-04-15',
       '2017-05-15', '2017-06-15', '2017-07-15', '2017-08-15',
       '2017-09-15', '2017-10-15', '2017-11-15', '2017-12-15',
       '2018-01-15', '2018-02-15', '2018-03-15', '2018-04-15',
       '2018-05-15', '2018-06-15', '2018-07-15', '2018-08-15',
       '2018-09-15', '2018-10-15', '2018-11-15', '2018-12-15',
       '2019-01-15', '2019-02-15', '2019-03-15', '2019-04-15',
       '2019-05-15', '2019-06-15', '2019-07-15', '2019-08-15',
       '2019-09-15', '2019-10-15', '2019-11-15', '2019-12-15',
       '2020-01-15', '2020-02-15', '2020-03-15', '2020-04-15',
       '2020-05-15', '2020-06-15', '2020-07-15', '2020-08-15',
       '2020-09-15', '2020-10-15', '2020-11-15', '2020-12-15',
       '2021-01-15', '2021-02-15', '2021-03-15', '2021-04-15',
       '2021-05-15', '2021-06-15', '2021-07-15', '2021-08-15',
       '2021-09-15', '2021-10-15', '2021-11-15', '2021-12-15',
       '2022-01-15', '2022-02-15', '2022-03-15', '2022-04-15',
       '2022-05-15', '2022-06-15', '2022-07-15', '2022-08-15',
       '2022-09-15', '2022-10-15', '2022-11-15', '2022-12-15',
       '2023-01-15', '2023-02-15', '2023-03-15', '2023-04-15',
       '2023-05-15', '2023-06-15', '2023-07-15', '2023-08-15',
       '2023-09-15', '2023-10-15', '2023-11-15', '2023-12-15',
       '2024-01-15', '2024-02-15', '2024-03-15', '2024-04-15',
       '2024-05-15', '2024-06-15', '2024-07-15', '2024-08-15',
       '2024-09-15', '2024-10-15', '2024-11-15', '2024-12-15',
       '2025-01-15', '2025-02-15', '2025-03-15', '2025-04-15',
       '2025-05-15', '2025-06-15', '2025-07-15', '2025-08-15',
       '2025-09-15', '2025-10-15', '2025-11-15', '2025-12-15',
       '2026-01-15', '2026-02-15', '2026-03-15', '2026-04-15',
       '2026-05-15'], dtype=object)

solution 1 - aggregate by date

### Indian rice prices (aggregate)

In [49]:
grouped_prices = rice_prices.groupby('date').agg(
    price=('price', 'mean'),
    usdprice=('usdprice', 'mean'),
    commodity=('commodity', 'first')
)

In [51]:
grouped_prices['2000-01-15':grouped_prices.index.max()]

                 price  usdprice commodity
date
2000-01-15  235.236111  5.411667      Rice
2000-02-15  213.895000  4.906000      Rice
2000-03-15  168.552632  3.875263      Rice
2000-04-15  200.420476  4.599048      Rice
2000-05-15  209.220000  4.777000      Rice
...                ...       ...       ...
2026-01-15   43.430000  0.480000      Rice
2026-02-15   43.477500  0.480000      Rice
2026-03-15   42.774000  0.464000      Rice
2026-04-15   43.127500  0.462500      Rice
2026-05-15   43.105000  0.447500      Rice

[317 rows x 3 columns]

In [13]:
dataset = grouped_prices.reset_index()

In [26]:
dataset.index = dataset.date

In [28]:
dataset.loc['2000-01-15':dataset.index.max()]

                  date  mean_price  mean_usdprice commodity
date
2000-01-15  2000-01-15  235.236111       5.411667      Rice
2000-02-15  2000-02-15  213.895000       4.906000      Rice
2000-03-15  2000-03-15  168.552632       3.875263      Rice
2000-04-15  2000-04-15  200.420476       4.599048      Rice
2000-05-15  2000-05-15  209.220000       4.777000      Rice
...                ...         ...            ...       ...
2026-01-15  2026-01-15   43.430000       0.480000      Rice
2026-02-15  2026-02-15   43.477500       0.480000      Rice
2026-03-15  2026-03-15   42.774000       0.464000      Rice
2026-04-15  2026-04-15   43.127500       0.462500      Rice
2026-05-15  2026-05-15   43.105000       0.447500      Rice

[317 rows x 4 columns]

In [32]:
dataset = dataset.loc['2000-01-15':dataset.index.max()]

In [37]:
dataset = dataset.reset_index(drop=True)

In [38]:
dataset

           date  mean_price  mean_usdprice commodity
0    2000-01-15  235.236111       5.411667      Rice
1    2000-02-15  213.895000       4.906000      Rice
2    2000-03-15  168.552632       3.875263      Rice
3    2000-04-15  200.420476       4.599048      Rice
4    2000-05-15  209.220000       4.777000      Rice
..          ...         ...            ...       ...
312  2026-01-15   43.430000       0.480000      Rice
313  2026-02-15   43.477500       0.480000      Rice
314  2026-03-15   42.774000       0.464000      Rice
315  2026-04-15   43.127500       0.462500      Rice
316  2026-05-15   43.105000       0.447500      Rice

[317 rows x 4 columns]

mean is inflated, there are 100kg unit entries which is multiplying a rice price 100x

### Tests

In [ ]:
df = pd.DataFrame({
    'Store': ['A', 'A', 'B', 'B'],
    'Sales': [100, 150, 200, 250],
    'Profit': [20, 35, 40, 60]
})

# Get the sum of all columns
df[['Sales', 'Profit']].agg('sum')

Sales     700
Profit    155
dtype: int64

In [ ]:
df[['Sales', 'Profit']].agg(['min', 'max'])

     Sales  Profit
min    100      20
max    250      60

In [ ]:
df.agg({'Sales': 'sum', 'Profit': 'mean'})

Sales     700.00
Profit     38.75
dtype: float64

In [ ]:
df.groupby('Store').agg(
    total_sales=('Sales', 'sum'),
    average_profit=('Profit', 'mean')
)

       total_sales  average_profit
Store
A              250            27.5
B              450            50.0